---
  - name: Update the machine
    command: sudo apt-get clean && update -y

  - name: Installing essentials
    apt: name={{ item }} state=present
    with_items:
    -  apt-transport-https
    -  ca-certificates
    -  curl
    -  software-properties-common

  - name: Adding Docker's offical GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Adding repository
    shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  - name: Updating system
    command: sudo apt-get update -y

  - name: Installing docker
    command: sudo apt-get install docker-ce -y

  - name: Adding docker user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart

  - name: Updating the machine 2
    command: sudo apt-get update

  - name: Installing Python Pip
    command: sudo apt-get install python-pip python-dev build-essential -y

  - name: Installing Docker compose
    command: sudo pip install docker-compose==1.3.0

  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    sudo: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    sudo: yes
    when: apt_result|failed
